Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2023
Var
numero, soma : real
contador : inteiro


Inicio
contador <- 1

para contador de 1 ate 10 faca
escreva("Digite o numero", contador, " :")
leia(numero)
soma <- soma + numero
fimPara

escreva("A soma dos 10 numeros é", soma, " :")


Fimalgoritmo