Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2023
Var
   contador: inteiro


Inicio
   Para contador de 0 ate 100 faca
      escreval(contador)
      se (contador % 10 = 0) entao
         escreval(" - Múltiplo de 10")
      senao
         escreval(contador)
      FimSe
   FimPara

Fimalgoritmo