Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2023
Var
   contador: inteiro


Inicio
   Para contador de 100 ate 200 faca
      se (contador % 2 = 1) entao
         escreval(contador)
      Fimse
   Fimpara


Fimalgoritmo