Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2023
Var
contador, numero : inteiro


Inicio
contador <- 1

escreval("Digite a tabuada desejada: ")
leia(numero)

enquanto(contador <= 10)faca
escreval(contador," x ", numero," = ", numero + contador)
contador <- contador + 1
fimEnquanto


Fimalgoritmo